---
title: "Kibrik and Kodzasov 1990 Database"
author: Viola Ivanova, Ilia Chechuro
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    css: style.css
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
knitr::opts_knit$set(global.device = TRUE)
```

*Authors: Viola Ivanova, Ilia Chechuro.*


##The Database

This database contains wordlists collected by Kibrik and Kodzasov (1990).

```{r, echo=FALSE, message=FALSE, warning=FALSE}

# loading packages
#Sys.setlocale("LC_TIME","ru_RU.UTF-8")
library(tidyverse)
library(DT)
library(lingtypology)
library(pcalg)
library(ggplot2)
library(pvclust)
library(dendextend)
library(UpSetR)
library(gridExtra)
library(lme4)

#library(fansi)


# loading data - mind the date in the csv filename!

words <- read_tsv("dataset_nouns_trans.tsv")
#words[sapply(words, is.character)] <- lapply(words[sapply(words, is.character)], as.factor)
words %>% datatable(class = 'cell-border stripe', 
          filter = 'top', 
          #options = list(pageLength = 100),
          extensions = 'Buttons', 
          options = list(
            autoWidth = TRUE,
            columnDefs = list(list(width = '50px', targets = c(1, 5))),
            pageLength = 10,
            dom = 'lBfrtip',
            buttons = c('copy', 'csv')))
```

##The Clusterization

This clusterization is based on the shared coding of meanings (lex_rus) across languages.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(data.table)
df <- words[,c(2,3,4)]
df <- setDT(df)[, list(class = paste(class, collapse = ' ')), 
            by = c('lang', 'lex_rus')]
df <- spread(df, lex_rus, class)
#View(df)
#write.csv(df, "nouns_wide.tsv", sep = "\t")
#View(head(df))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(pvclust)
dst <- read_tsv("KiKo_dist.tsv")
rnames <- dst$Speaker
dst <- dst[,-1]
row.names(dst) <- rnames
dst <- as.dist(dst)
result <- pvclust::pvclust(as.matrix(dst), method.hclust="average", nboot=100, quiet=TRUE)
dend <- as.dendrogram(result)
dend %>%
   pvclust_show_signif_gradient(result) %>%
   pvclust_show_signif(result) %>%
   plot(main = "Cluster Dendrogram of Class Assignment")
result %>% text (cex = 0.5) 
result %>% pvrect(alpha=0.95)
```

##NNet

The NeighborNet is built with the same data.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(phangorn)
plot(neighborNet(dst),"2D")
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_t <- t(df)
cnames <- df_t[1,]
df_t <- df_t[-1,]
colnames(df_t) <- cnames
#View(df)
#write.csv(df_t, "meanings_wide.tsv", sep = "\t")
#View(head(df))
```

##Clusterization of meanings

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(pvclust)
dst_meanings <- read_tsv("KiKo_meanings_dist.tsv")
rnames_meanings <- dst_meanings$Speaker
dst_meanings$lex_rus <- dst_meanings$Speaker
rus <- words[,c(2,14,15)]
rus <- rus[!duplicated(rus),]            
colors_to_use <- left_join(dst_meanings,rus,by = c("lex_rus"))
dst_meanings <- dst_meanings[,-1]
row.names(dst_meanings) <- rnames_meanings
dst_meanings <- as.dist(dst_meanings)
colors_to_use$semantics_KK_detailed <- factor(colors_to_use$semantics_KK_detailed)
colors_to_use$semantics_KK <- factor(colors_to_use$semantics_KK)

MDS <- cmdscale(dst_meanings,eig=TRUE, k=2)
x <- MDS$points[,1]
y <- MDS$points[,2]
p1 <- ggplot(data = colors_to_use, aes(x = MDS$points[,1], y = MDS$points[,2])) + 
    geom_text(aes(color = colors_to_use$semantics_KK_detailed, label = colors_to_use$Speaker))
p2 <- ggplot(data = colors_to_use, aes(x = MDS$points[,1], y = MDS$points[,2])) + 
    geom_text(aes(color = colors_to_use$semantics_KK, label = colors_to_use$Speaker))
library(plotly)
ggplotly(p2)

```
